# Generated by Django 2.2 on 2019-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
